services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: max
      MONGO_INITDB_ROOT_PASSWORD: secret
  backend:
    build: ./backend
    volumes:
      - logs:/logs
      - /backend/node_modules
    ports:
      - 80:80
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    volumes:
      - /frontend/src:/backend/src
    ports:
      - 3000:3000
volumes:
  data:
  logs:
